import * as skills from './library/skills.js';
import * as world from './library/world.js';
import * as combat from './library/combat.js';
import * as magic from './library/magic.js';
import * as npcDefense from './library/npc_defense.js';
import * as society from './library/society.js';
import * as survival from './library/survival.js';
import * as decisionGraph from './library/decision_graph.js';
import * as mc from '../utils/mcdata.js';
import settings from './settings.js';
import convoManager from './conversation.js';

const MODE_FOOD = ['bread', 'cooked_beef', 'cooked_porkchop', 'cooked_chicken', 'cooked_mutton',
    'baked_potato', 'apple', 'carrot', 'golden_carrot', 'cooked_cod', 'cooked_salmon',
    'beef', 'porkchop', 'chicken', 'mutton'];

// Behavior narration is generated by modes that tick constantly (e.g. self_defense
// fires "Fighting Zombie!" every update while a mob is near), which floods chat. We
// still record every line to behavior_log, but throttle what actually reaches chat:
//   - the same line is not repeated within SAY_DEDUP_MS
//   - at most one behavior line per SAY_MIN_GAP_MS per bot
// This only affects narration; the underlying action (fighting, escaping) still runs.
const SAY_DEDUP_MS = 15000;
const SAY_MIN_GAP_MS = 2500;
const MODE_SAFETY_GOALS = Object.freeze({
    self_preservation: 'escapeHazard',
    emergency_nutrition: 'foodRecovery',
    unstuck: 'stuckRecovery',
    cowardice: 'escapeThreat',
    self_defense: 'combat',
    npc_defense: 'combat',
});
const MODE_SAFETY_PRIORITIES = Object.freeze({
    self_preservation: 100,
    emergency_nutrition: 90,
    cowardice: 80,
    npc_defense: 70,
    self_defense: 60,
    unstuck: 40,
});

export function shouldFleeRecentDamage(bot, hasNearbyThreat = false, now = Date.now()) {
    const recentDangerousDamage = now - Number(bot.lastDamageTime ?? 0) < 3000
        && (Number(bot.health ?? 20) < 10
            || Number(bot.lastDamageTaken ?? 0) >= Number(bot.health ?? 20));
    if (!recentDangerousDamage) return false;

    // Starvation damage has no attacker. Treating it like an ambush made an
    // empty-hunger bot run 20 blocks after every damage tick, permanently
    // pre-empting the deterministic food recovery action.
    return Number(bot.food ?? 20) > 0 || hasNearbyThreat;
}

function say(agent, message) {
    agent.bot.modes.behavior_log += message + '\n';
    if (agent.shut_up || !settings.narrate_behavior) return;
    const now = Date.now();
    const st = agent._sayState || (agent._sayState = { last: 0, recent: new Map() });
    const lastSeen = st.recent.get(message);
    if (lastSeen && now - lastSeen < SAY_DEDUP_MS) return; // exact duplicate, too soon
    if (now - st.last < SAY_MIN_GAP_MS) return;            // global per-bot rate limit
    st.last = now;
    st.recent.set(message, now);
    if (st.recent.size > 40) { // prune stale dedup entries
        for (const [k, t] of st.recent) if (now - t > SAY_DEDUP_MS) st.recent.delete(k);
    }
    void agent.openChat(message).catch(() => {});
}

// a mode is a function that is called every tick to respond immediately to the world
// it has the following fields:
// on: whether 'update' is called every tick
// active: whether an action has been triggered by the mode and hasn't yet finished
// paused: whether the mode is paused by another action that overrides the behavior (eg followplayer implements its own self defense)
// update: the function that is called every tick (if on is true)
// when a mode is active, it will trigger an action to be performed but won't wait for it to return output

// the order of this list matters! first modes will be prioritized
// while update functions are async, they should *not* be awaited longer than ~100ms as it will block the update loop
// to perform longer actions, use the execute function which won't block the update loop
const modes_list = [
    {
        name: 'self_preservation',
        description: 'Respond to drowning, burning, and damage at low health. Interrupts all actions.',
        interrupts: ['all'],
        on: true,
        active: false,
        water_since: 0,
        last_water_escape: 0,
        fall_blocks: ['sand', 'gravel', 'concrete_powder'], // includes matching substrings like 'sandstone' and 'red_sand'
        update: function (agent) {
            const bot = agent.bot;
            let block = bot.blockAt(bot.entity.position);
            let blockAbove = bot.blockAt(bot.entity.position.offset(0, 1, 0));
            if (!block) block = {name: 'air'}; // hacky fix when blocks are not loaded
            if (!blockAbove) blockAbove = {name: 'air'};
            const inWater = skills.isBotInWater(bot);
            if (inWater) {
                this.water_since ||= Date.now();
                const waterTravelActive = bot._waterTravelActive === true || skills.isBotInBoat(bot);
                const submerged = blockAbove.name === 'water'
                    || blockAbove.name === 'bubble_column'
                    || Number(bot.oxygenLevel ?? 20) < 18;
                const lingering = Date.now() - this.water_since > 2500;
                if (waterTravelActive && Number(bot.oxygenLevel ?? 20) > 10 && !submerged) {
                    bot.setControlState('sprint', false);
                    bot.setControlState('jump', true);
                    return;
                }
                if ((submerged || lingering)
                    && Date.now() - this.last_water_escape > 3000) {
                    this.last_water_escape = Date.now();
                    if (submerged) say(agent, 'Grem ven iz vode.');
                    void execute(this, agent, async () => await skills.escapeWater(bot));
                } else {
                    // Keep gaining height while the dedicated escape action waits
                    // for the currently-running action manager to yield.
                    bot.setControlState('sprint', false);
                    bot.setControlState('jump', true);
                }
                return;
            }
            this.water_since = 0;
            bot.setControlState('jump', false);
            if (this.fall_blocks.some(name => blockAbove.name.includes(name))) {
                void execute(this, agent, async () => {
                    await skills.moveAway(bot, 2);
                });
            }
            else if (block.name === 'lava' || block.name === 'fire' ||
                blockAbove.name === 'lava' || blockAbove.name === 'fire') {
                say(agent, 'I\'m on fire!');
                // if you have a water bucket, use it
                let waterBucket = mc.findInventoryItem(bot, 'water_bucket');
                if (waterBucket) {
                    void execute(this, agent, async () => {
                        let success = await skills.placeBlock(bot, 'water_bucket', block.position.x, block.position.y, block.position.z);
                        if (success) say(agent, 'Placed some water, ahhhh that\'s better!');
                    });
                }
                else {
                    void execute(this, agent, async () => {
                        let waterBucket = mc.findInventoryItem(bot, 'water_bucket');
                        if (waterBucket) {
                            let success = await skills.placeBlock(bot, 'water_bucket', block.position.x, block.position.y, block.position.z);
                            if (success) say(agent, 'Placed some water, ahhhh that\'s better!');
                            return;
                        }
                        let nearestWater = world.getNearestBlock(bot, 'water', 20);
                        if (nearestWater) {
                            const pos = nearestWater.position;
                            let success = await skills.goToPosition(bot, pos.x, pos.y, pos.z, 0.2);
                            if (success) say(agent, 'Found some water, ahhhh that\'s better!');
                            return;
                        }
                        await skills.moveAway(bot, 5);
                    });
                }
            }
            else if (shouldFleeRecentDamage(
                bot,
                Number(bot.food ?? 20) <= 0 && npcDefense.currentThreat(agent) != null,
            )) {
                say(agent, 'I\'m dying!');
                void execute(this, agent, async () => {
                    await skills.moveAway(bot, 20);
                });
            }
            else if (agent.isIdle()) {
                bot.clearControlStates(); // clear jump if not in danger or doing anything else
            }
        }
    },
    {
        name: 'emergency_nutrition',
        description: 'Interrupt long work when hunger is critically low and secure food immediately.',
        interrupts: ['all'],
        on: true,
        active: false,
        update: function (agent) {
            const bot = agent.bot;
            if (!survival.needsEmergencyNutrition(bot)) return;
            say(agent, 'Prekinjam delo — nujno potrebujem hrano.');
            void execute(this, agent, async () => await survival.secureFood(bot), 2);
        }
    },
    {
        name: 'unstuck',
        description: 'Attempt to get unstuck when in the same place for a while. Interrupts some actions.',
        interrupts: ['all'],
        on: true,
        active: false,
        prev_location: null,
        distance: 2,
        stuck_time: 0,
        last_time: Date.now(),
        max_stuck_time: 20,
        prev_dig_block: null,
        last_recovery: 0,
        update: function (agent) {
            if (agent.isIdle()) { 
                this.prev_location = null;
                this.stuck_time = 0;
                return; // don't get stuck when idle
            }
            const bot = agent.bot;
            const cur_dig_block = bot.targetDigBlock;
            if (cur_dig_block && !this.prev_dig_block) {
                this.prev_dig_block = cur_dig_block;
            }
            if (this.prev_location && this.prev_location.distanceTo(bot.entity.position) < this.distance && cur_dig_block == this.prev_dig_block) {
                this.stuck_time += (Date.now() - this.last_time) / 1000;
            }
            else {
                this.prev_location = bot.entity.position.clone();
                this.stuck_time = 0;
                this.prev_dig_block = null;
            }
            const max_stuck_time = cur_dig_block?.name === 'obsidian' ? this.max_stuck_time * 2 : this.max_stuck_time;
            if (this.stuck_time > max_stuck_time && Date.now() - this.last_recovery > 15000) {
                say(agent, 'I\'m stuck!');
                this.stuck_time = 0;
                this.last_recovery = Date.now();
                void execute(this, agent, async () => {
                    bot.pathfinder.stop();
                    bot.clearControlStates();
                    bot.setControlState('jump', true);
                    await new Promise(resolve => setTimeout(resolve, 350));
                    bot.setControlState('jump', false);
                    const moved = await skills.moveAway(bot, 3);
                    say(agent, moved ? 'I\'m free.' : 'I\'ll try another route.');
                });
            }
            this.last_time = Date.now();
        },
        unpause: function () {
            this.prev_location = null;
            this.stuck_time = 0;
            this.prev_dig_block = null;
        }
    },
    {
        name: 'cowardice',
        description: 'Run away from enemies. Interrupts all actions.',
        interrupts: ['all'],
        on: true,
        active: false,
        update: async function (agent) {
            const enemy = world.getNearestEntityWhere(agent.bot, entity => mc.isHostile(entity), 16);
            if (!enemy) return;
            // A healthy magician has a built-in ranged attack even without a bow,
            // shield or sword, so cowardice must not preempt the spell cast.
            if (society.getRole(agent) === 'magician'
                && skills.canFightAtCurrentHealth(agent.bot))
                return;
            // An armed, healthy fighter holds its ground (self_defense handles the
            // fight); only flee when hurt or without a usable weapon.
            if (skills.canFightAtCurrentHealth(agent.bot) && combat.willStandGround(agent, enemy))
                return;
            if (await world.isClearPath(agent.bot, enemy)) {
                say(agent, `Aaa! A ${enemy.name.replace("_", " ")}!`);
                void execute(this, agent, async () => {
                    await skills.avoidEnemies(agent.bot, 24);
                });
            }
        }
    },
    {
        name: 'self_defense',
        description: 'Attack nearby enemies. Interrupts all actions.',
        interrupts: ['all'],
        on: true,
        active: false,
        update: async function (agent) {
            if (combat.getCombatStance(agent) === 'passive') return;
            if (!skills.canFightAtCurrentHealth(agent.bot)) {
                try { agent.bot.pvp?.stop?.(); } catch { /* disconnected */ }
                return;
            }
            const range = combat.getCombatStance(agent) === 'aggressive' ? 18 : 12;
            const enemy = world.getNearestEntityWhere(agent.bot, entity => mc.isHostile(entity), range);
            if (enemy && await world.isClearPath(agent.bot, enemy)) {
                if (society.getRole(agent) === 'magician') {
                    if (Date.now() - (agent._brain?.magicianSpell ?? 0) < magic.magicianCastCooldownMs())
                        return;
                    say(agent, `Casting a fireball at ${enemy.name}!`);
                    void execute(this, agent, async () => {
                        const cast = await magic.castFireball(agent, enemy);
                        if (cast && agent._brain) agent._brain.magicianSpell = Date.now();
                        return cast;
                    });
                    return;
                }
                say(agent, `Fighting ${enemy.name}!`);
                void execute(this, agent, async () => {
                    // Archers loose a few arrows while the mob is still at range,
                    // then everyone finishes the fight in melee. Defenders raise a
                    // shield first so defendSelf's blows are backed by blocking.
                    if (combat.getCombatStyle(agent) === 'archer') {
                        let shots = 0;
                        while (combat.canShootBow(agent.bot, enemy)
                            && !agent.bot.interrupt_code && shots < 3) {
                            if (!await combat.shootBowAt(agent.bot, enemy)) break;
                            shots++;
                        }
                    } else if (agent.bot.inventory.items().some(item => item.name === 'shield')) {
                        try { await skills.equip(agent.bot, 'shield'); } catch { /* melee still works */ }
                    }
                    // Engage at the SAME range the mode detected the enemy (12 normal /
                    // 18 aggressive). Passing a smaller fixed range made defendSelf find
                    // nothing for a mob detected in the 9–18 band, so it interrupted work
                    // and then no-op'd every 300ms tick ("No enemies nearby to defend
                    // self from") — a churn that broke mining/farming and reset the stuck
                    // watchdogs. defendSelf closes the gap itself via GoalFollow.
                    await skills.defendSelf(agent.bot, range);
                });
            }
        }
    },
    {
        name: 'npc_defense',
        description: 'React in self-defense to modded NPC / player attackers (which vanilla self_defense misses) and help attacked allies. Interrupts all actions.',
        interrupts: ['all'],
        on: true,
        active: false,
        update: function (agent) {
            const bot = agent.bot;
            npcDefense.ensureNpcDefense(agent);
            const threat = npcDefense.currentThreat(agent);
            if (!threat) return;
            if (combat.getCombatStance(agent) === 'passive') return;
            const label = npcDefense.threatLabel(threat);
            if (!skills.canFightAtCurrentHealth(bot)) {
                // too hurt to trade blows — back off from the attacker instead
                say(agent, `Prevec sem ranjen — umikam se pred ${label}!`);
                void execute(this, agent, async () => { await skills.moveAwayFromEntity(bot, threat, 12); });
                return;
            }
            if (society.getRole(agent) === 'magician') {
                if (Date.now() - (agent._brain?.magicianSpell ?? 0) < magic.magicianCastCooldownMs())
                    return;
                say(agent, `Casting a fireball at ${label}!`);
                void execute(this, agent, async () => {
                    const cast = await magic.castFireball(agent, threat);
                    if (cast && agent._brain) agent._brain.magicianSpell = Date.now();
                    return cast;
                });
                return;
            }
            if (!combat.willStandGround(agent, threat)) {
                // A fresh respawn is healthy but usually unarmed. Charging a modded
                // horror bare-handed caused immediate repeat-death loops; retreat
                // until the deterministic brain restores a real combat kit.
                say(agent, `Nimam opreme za boj — umikam se pred ${label}!`);
                void execute(this, agent, async () => { await skills.moveAwayFromEntity(bot, threat, 16); });
                return;
            }
            say(agent, `${label} napada — branim se!`);
            void execute(this, agent, async () => { await skills.attackEntity(bot, threat, true); });
        }
    },
    {
        name: 'hunting',
        description: 'Hunt nearby animals when idle.',
        interrupts: ['action:followPlayer'],
        on: true,
        active: false,
        update: async function (agent) {
            if (!skills.canFightAtCurrentHealth(agent.bot)) return;
            if (Number(agent.bot.food ?? 20) > 14) return;
            const food = world.getInventoryCounts(agent.bot);
            const foodCount = MODE_FOOD.reduce((sum, name) => sum + (food[name] ?? 0), 0);
            if (foodCount >= 3) return;
            const nearbyAdults = Object.values(agent.bot.entities ?? {})
                .filter(entity => mc.isHuntable(entity)
                    && entity.position?.distanceTo(agent.bot.entity.position) <= 8);
            const huntable = nearbyAdults.find(entity =>
                nearbyAdults.filter(other => other.name === entity.name).length >= 3);
            if (huntable && await world.isClearPath(agent.bot, huntable)) {
                void execute(this, agent, async () => {
                    say(agent, `Hunting ${huntable.name}!`);
                    await skills.attackEntity(agent.bot, huntable);
                });
            }
        }
    },
    {
        name: 'item_collecting',
        description: 'Collect nearby items when idle.',
        interrupts: ['action:followPlayer'],
        on: true,
        active: false,

        wait: 2, // number of seconds to wait after noticing an item to pick it up
        prev_item: null,
        noticed_at: -1,
        update: async function (agent) {
            let item = world.getNearestEntityWhere(agent.bot, entity => entity.name === 'item', 8);
            let empty_inv_slots = agent.bot.inventory.emptySlotCount();
            if (item && item !== this.prev_item && await world.isClearPath(agent.bot, item) && empty_inv_slots > 1) {
                if (this.noticed_at === -1) {
                    this.noticed_at = Date.now();
                }
                if (Date.now() - this.noticed_at > this.wait * 1000) {
                    say(agent, `Picking up item!`);
                    this.prev_item = item;
                    void execute(this, agent, async () => {
                        await skills.pickupNearbyItems(agent.bot);
                    });
                    this.noticed_at = -1;
                }
            }
            else {
                this.noticed_at = -1;
            }
        }
    },
    {
        name: 'torch_placing',
        description: 'Place torches when idle and there are no torches nearby.',
        interrupts: ['action:followPlayer'],
        on: true,
        active: false,
        cooldown: 5,
        last_place: Date.now(),
        update: function (agent) {
            if (world.shouldPlaceTorch(agent.bot)) {
                if (Date.now() - this.last_place < this.cooldown * 1000) return;
                void execute(this, agent, async () => {
                    const pos = agent.bot.entity.position;
                    await skills.placeBlock(agent.bot, 'torch', pos.x, pos.y, pos.z, 'bottom', true);
                });
                this.last_place = Date.now();
            }
        }
    },
    {
        name: 'elbow_room',
        description: 'Move away from nearby players when idle.',
        interrupts: ['action:followPlayer'],
        on: true,
        active: false,
        distance: 0.5,
        last_move: 0,
        update: function (agent) {
            if (Date.now() - this.last_move < 3000) return;
            const player = world.getNearestEntityWhere(agent.bot, entity => entity.type === 'player', this.distance);
            if (player) {
                this.last_move = Date.now();
                void execute(this, agent, async () => {
                    // wait a random amount of time to avoid identical movements with other bots
                    const wait_time = Math.random() * 1000;
                    await new Promise(resolve => setTimeout(resolve, wait_time));
                    if (player.position.distanceTo(agent.bot.entity.position) < this.distance) {
                        await skills.moveAwayFromEntity(agent.bot, player, this.distance);
                    }
                });
            }
        }
    },
    {
        name: 'idle_staring',
        description: 'Animation to look around at entities when idle.',
        interrupts: [],
        on: true,
        active: false,

        staring: false,
        last_entity: null,
        next_change: 0,
        last_look: 0,
        update: async function (agent) {
            const entity = agent.bot.nearestEntity();
            let entity_in_view = entity && entity.position.distanceTo(agent.bot.entity.position) < 10 && entity.name !== 'enderman';
            if (entity_in_view && entity !== this.last_entity) {
                this.staring = true;
                this.last_entity = entity;
                this.next_change = Date.now() + Math.random() * 1000 + 4000;
            }
            if (entity_in_view && this.staring && Date.now() - this.last_look > 1000) {
                let isbaby = entity.type !== 'player' && mc.isBabyEntity(entity, agent.bot);
                let height = isbaby ? entity.height/2 : entity.height;
                this.last_look = Date.now();
                try { await agent.bot.lookAt(entity.position.offset(0, height, 0)); } catch { /* entity moved */ }
            }
            if (!entity_in_view)
                this.last_entity = null;
            if (Date.now() > this.next_change) {
                // look in random direction
                this.staring = Math.random() < 0.3;
                if (!this.staring) {
                    const yaw = Math.random() * Math.PI * 2;
                    const pitch = (Math.random() * Math.PI/2) - Math.PI/4;
                    try { await agent.bot.look(yaw, pitch, false); } catch { /* disconnected */ }
                }
                this.next_change = Date.now() + Math.random() * 10000 + 2000;
            }
        }
    },
    {
        name: 'cheat',
        description: 'Use cheats to instantly place blocks and teleport.',
        interrupts: [],
        on: false,
        active: false,
        update: function (agent) { /* do nothing */ }
    }
];

async function execute(mode, agent, func, timeout=-1) {
    if (agent.self_prompter.isActive())
        agent.self_prompter.stopLoop();
    if (settings.deterministic_brain && mode.interrupts.includes('all')) {
        const queued = decisionGraph.queueSafetyAction(agent, {
            key: `mode:${mode.name}`,
            goalKey: MODE_SAFETY_GOALS[mode.name] ?? `mode:${mode.name}`,
            priority: MODE_SAFETY_PRIORITIES[mode.name] ?? 50,
            reason: mode.description,
            createAction: () => ({
                name: `mode:${mode.name}`,
                timeout,
                fn: async () => {
                    mode.pending = false;
                    mode.active = true;
                    try { return await func(); }
                    finally { mode.active = false; }
                },
            }),
            onDiscard: () => { mode.pending = false; },
        });
        if (queued) mode.pending = true;
        return;
    }
    let interrupted_action = agent.actions.currentActionLabel;
    mode.active = true;
    let code_return;
    try {
        code_return = await agent.actions.runAction(`mode:${mode.name}`, async () => {
            return await func();
        }, { timeout });
    } finally {
        mode.active = false;
    }
    console.log(`Mode ${mode.name} finished executing, code_return: ${code_return.message}`);

    let should_reprompt = 
        interrupted_action && // it interrupted a previous action
        !settings.deterministic_brain && // deterministic brain retries without another LLM call
        !agent.actions.resume_func && // there is no resume function
        !agent.self_prompter.isActive() && // self prompting is not on
        !code_return.interrupted; // this mode action was not interrupted by something else

    if (should_reprompt) {
        // auto prompt to respond to the interruption
        let role = convoManager.inConversation() ? agent.last_sender : 'system';
        let logs = agent.bot.modes.flushBehaviorLog();
        void agent.enqueueMessage(role, `(AUTO MESSAGE)Your previous action '${interrupted_action}' was interrupted by ${mode.name}.
        Your behavior log: ${logs}\nRespond accordingly.`).catch(error => {
            console.error('Failed to queue mode interruption message:', error);
        });
    }
}

let _agent = null;
const modes_map = {};
for (let mode of modes_list) {
    modes_map[mode.name] = mode;
}

class ModeController {
    /*
    SECURITY WARNING:
    ModesController must be reference isolated. Do not store references to external objects like `agent`.
    This object is accessible by LLM generated code, so any stored references are also accessible.
    This can be used to expose sensitive information by malicious prompters.
    */
    constructor() {
        this.behavior_log = '';
    }

    exists(mode_name) {
        return modes_map[mode_name] != null;
    }

    setOn(mode_name, on) {
        modes_map[mode_name].on = on;
    }

    isOn(mode_name) {
        return modes_map[mode_name].on;
    }

    pause(mode_name) {
        modes_map[mode_name].paused = true;
    }

    unpause(mode_name) {
        const mode = modes_map[mode_name];
        //if  unpause func is defined and mode is currently paused
        if (mode.unpause && mode.paused) {
            mode.unpause();
        }
        mode.paused = false;
    }

    unPauseAll() {
        for (let mode of modes_list) {
            if (mode.paused) console.log(`Unpausing mode ${mode.name}`);
            this.unpause(mode.name);
        }
    }

    getMiniDocs() { // no descriptions
        let res = 'Agent Modes:';
        for (let mode of modes_list) {
            let on = mode.on ? 'ON' : 'OFF';
            res += `\n- ${mode.name}(${on})`;
        }
        return res;
    }

    getDocs() {
        let res = 'Agent Modes:';
        for (let mode of modes_list) {
            let on = mode.on ? 'ON' : 'OFF';
            res += `\n- ${mode.name}(${on}): ${mode.description}`;
        }
        return res;
    }

    async update() {
        if (_agent.isIdle()) {
            this.unPauseAll();
        }
        for (let mode of modes_list) {
            let interruptible = mode.interrupts.some(i => i === 'all') || mode.interrupts.some(i => i === _agent.actions.currentActionLabel);
            if (mode.on && !mode.paused && !mode.active && !mode.pending && (_agent.isIdle() || interruptible)) {
                await mode.update(_agent);
            }
            if (mode.active || mode.pending) break;
        }
    }

    flushBehaviorLog() {
        const log = this.behavior_log;
        this.behavior_log = '';
        return log;
    }

    getJson() {
        let res = {};
        for (let mode of modes_list) {
            res[mode.name] = mode.on;
        }
        return res;
    }

    loadJson(json) {
        for (let mode of modes_list) {
            if (json[mode.name] != undefined) {
                mode.on = json[mode.name];
            }
        }
    }
}

export function initModes(agent) {
    _agent = agent;
    // the mode controller is added to the bot object so it is accessible from anywhere the bot is used
    agent.bot.modes = new ModeController();
    if (agent.task) {
        agent.bot.restrict_to_inventory = agent.task.restrict_to_inventory;
    }
    let modes_json = agent.prompter.getInitModes();
    if (modes_json) {
        agent.bot.modes.loadJson(modes_json);
    }
}
